# Generated by Django 5.1.7 on 2025-03-27 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('Zona Cero', 'Zona Cero'), ('RM', 'RM')], default='RM', max_length=20, null=True),
        ),
    ]
