# Generated by Django 5.1.7 on 2025-03-27 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_profile_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='lastface',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='faces', to='core.profile'),
            preserve_default=False,
        ),
    ]
