# Generated by Django 5.1.7 on 2025-03-27 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_lastface_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
