# Generated by Django 5.1.7 on 2025-04-09 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_profile_assigned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('Alta', 'Alta'), ('Baja', 'Baja')], default='Baja', max_length=20, null=True),
        ),
    ]
