# Generated by Django 5.1.7 on 2025-04-01 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_trips'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Trips',
        ),
    ]
