# Generated by Django 5.1.7 on 2025-04-17 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_profile_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailabilitySnapshotHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('present_snapshot', models.BooleanField(default=False)),
                ('assigned_snapshot', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_snapshots', to='core.profile')),
            ],
        ),
    ]
