# Generated by Django 5.2 on 2025-07-02 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_profile_image_base64'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Patente',
            field=models.CharField(default='HHMM77', max_length=6),
        ),
        migrations.CreateModel(
            name='SoapApiLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fh_ingreso', models.CharField(max_length=20)),
                ('cod_site', models.CharField(max_length=10)),
                ('rut_conductor', models.CharField(max_length=20)),
                ('nom_conductor', models.CharField(max_length=200)),
                ('tracto', models.CharField(blank=True, max_length=20)),
                ('rut_transporte', models.CharField(blank=True, max_length=20)),
                ('nom_transporte', models.CharField(blank=True, max_length=200)),
                ('estado', models.CharField(choices=[('SUCCESS', 'Éxito'), ('FAILED', 'Fallido'), ('UNKNOWN', 'Desconocido')], max_length=10)),
                ('respuesta_api', models.TextField()),
                ('error_mensaje', models.TextField(blank=True, null=True)),
                ('http_status', models.IntegerField(blank=True, null=True)),
                ('fecha_llamada', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soap_logs', to='core.profile')),
            ],
            options={
                'verbose_name': 'Registro API SOAP',
                'verbose_name_plural': 'Registros API SOAP',
                'ordering': ['-fecha_llamada'],
            },
        ),
    ]
