# Generated by Django 5.1.7 on 2025-04-14 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_profile_status'),
        ('core', '0009_profile_image_base64'),
    ]

    operations = [
    ]
